azs:
- cloud_properties:
    datacenters:
    - clusters:
      - Cluster: {}
  name: z1
- cloud_properties:
    datacenters:
    - clusters:
      - Cluster: {}
  name: z2
- cloud_properties:
    datacenters:
    - clusters:
      - Cluster: {}
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 5
disk_types:
- disk_size: 3000
  name: default
- disk_size: 60000
  name: large
networks:
- name: default
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: VM Network
    dns:
    - 10.193.56.2
    gateway: 10.193.56.1
    range: 10.193.56.0/24
    #static: [10.193.56.101-10.193.56.110]
    reserved: [10.193.56.0-10.193.56.100,10.193.56.240-10.193.56.249]
  type: manual
vm_types:
- cloud_properties:
    cpu: 2
    disk: 3240
    ram: 1024
  name: default
- cloud_properties:
    cpu: 2
    disk: 60000
    ram: 4096
  name: large


